### ISSUE TITLE
MAF filter default between plink and gnocchi equal

### ISSUE THREAD

**Issue by nathanielparke** [bigdatagenomics/gnocchi#16]
In running concordance results, there are a few differences in the output from plink and gnocchi on the standard SSRI dataset. The plink results are missing certain SNP's that gnocchi ranks highly amongst the logistic regression. We have now ruled out any discrepancies between plink and gnocchi's phenotype filtering so this indicates that the difference in results must be due to genotype filtering.

**Comment by tkdagdelen** [comment]
covered by #22
