### ISSUE TITLE
Repository cleanup

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/gnocchi#5]
Suggestions for repository cleanup:

rename `Gnocchi-test` &rarr; `gnocchi-test`
remove `Gnocchi-test/src/main/scala/org/maventest`
remove `Gnocchi-test/test/scala/samples`
remove `TestDataResults` or move into `gnocchi-test/src/test/resources`
remove `gnocchi-cli/.src`
remove `gnocchi-cli/TestDataResults` or move into `gnocchi-cli/src/test/resources`
remove `gnocchi-cli/parquetFiles` or move into `gnocchi-cli/src/test/resources`
remove `gnocchi-cli/src/test/resources/metastore_db`
remove `metastore_db`
remove `parquetFiles` or move into `gnocchi-test/src/test/resources`
remove `parquetVersion` or move into `gnocchi-test/src/test/resources`
remove `testData` or move into `gnocchi-test/src/test/resources`
move `ADAMKryoRegistrator.scala` into `gnocchi-core/src/main/scala` hierarchy
move `GnocchiFunSuite.scala` into `gnocchi-core/src/test/scala` hierarchy
remove `Gnocchi_README.md`
move `fixPheno4Gnocchi.py` into `bin` or `scripts`
move `fixVCF4Gnocchi.py` into `bin` or `scripts`
remove `gnocchi-parent.iml`

Note in general we try not to check in binary files for tests (e.g. Parquet folders), since we can't see diffs if test data ever need to change.

**Comment by heuermh** [comment]
Some changes were made in #12

**Comment by tkdagdelen** [comment]
covered in #25
